accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('profile', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

job/urls.py
from django.urls import path
from . import views

app_name = 'job'

urlpatterns = [
    path('', views.job_list, name='job_list'),
    path('add_job',views.add_job,name='add_job'),
    path('<str:slug>', views.job_detail, name='job_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('contact-us/',include('contact.urls',namespace='contact')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls',namespace='jobs'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid

def image_upload(instance,filename):
    imagename, extansion = filename.split('.')
    return f'profile/{uuid.uuid4()}.{extansion}'

# Create your models here.######################

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    city = models.ForeignKey('City', related_name='user_city', on_delete=models.CASCADE,blank=True,null=True)
    number_phone = models.CharField(max_length=15)
    image = models.ImageField(upload_to=image_upload)

    def __str__(self):
        return str(self.user)

#########################################################################

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

#########################################################################

class City(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignupUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city','number_phone','image']

accounts/views.py
from django.shortcuts import render,redirect
from .forms import SignupUserForm, UserForm, ProfileForm
from django.contrib.auth import authenticate, login
from .models import Profile
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = SignupUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request,username=username,password=password)
            login(request,user)
            return redirect('accounts:profile')

    else:
        form = SignupUserForm()

    context = {
        'form': form,
    }
    return render(request,'registration/signup.html',context)

#####################################################################
@login_required
def profile(request):
    profile = Profile.objects.get(user=request.user)
    context = {
        'profile':profile,
    }
    return render(request,'accounts/profile.html',context)

#####################################################################
@login_required
def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        userform = UserForm(request.POST,instance=request.user)
        profileform = ProfileForm(request.POST,request.FILES,instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile = profileform.save(commit=False)
            myprofile.user = request.user
            myprofile.save()
            return redirect('accounts:profile')
    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)

    context = {
        'userform': userform,
        'profileform': profileform,
    }
    return render(request,'accounts/profile_edit.html',context)

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>name: <span>{{profile}}</span></li>
                                <li>email: <span>{{profile.user.email}}</span></li>
                                <li>address: <span>{{profile.city}}</span></li>
                                <li>phone: <span>{{profile.number_phone}}</span></li>
                            </ul>
                        </div>
                        <div class="p-5">
                            <a href="{% url 'accounts:profile_edit'%}">Edit Profile</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

accounts/templates/accounts/profile_edit.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form userform %}
    {% bootstrap_form profileform %}
    <input type="submit" class="boxed-btn3 w-100" value="Save" />
  </form>
{% endblock %}